jobs:
  include:
    - stage: install
      language: node_js
      node_js:
        - 14
      install:
        - cd svelte_client
        - npm install
        - npm run build
    - stage: install
      language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
